version: "3.8"
services:
  mysql:
    image: mysql:5.7
    working_dir: /application
    volumes:
      - ../:/application
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
      - MYSQL_DATABASE=test

  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ../:/application
      - "./nginx/config/$DOCKER_ENV/default.conf:/etc/nginx/conf.d/default.conf"
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"

  php:
    build: php-fpm
    working_dir: /application
    volumes:
      - ../:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
